name: Bug Report
description: Report a bug/issue that you found in the App
title: '[BUG] <bug name>'
labels: [bug-with-app]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Short description of the bug that you found. Provide images/code if applicable.
    validations:
      required: true
  - type: textarea
    id: howtoreplicate
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue
    validations:
      required: true