name: Suggest a feature (Game Handler)
description: Suggest a new feature for a given game handler. For example support for different input, or different game store (EG, GOG, Steam, etc..)
title: '[FEATURE] <handler name> <feature name>'
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Short description of the feature you want added. Provide images/code if applicable.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why do you want this feature?
      description: Tell us why you want/need this feature, and why it would be useful
    validations:
      required: true
  - type: textarea
    id: extrainformation
    attributes:
      label: Additional information
      description: Is there anything else we should know about this feature? Feel free to explain in depth here
    validations:
      required: false